# Generated by Django 6.0.5 on 2026-05-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomadicode_auth", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="otpcode",
            new_name="nomadicode__phone_5b6fe6_idx",
            old_name="nomadicode__phone_p_idx",
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
